# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: Build Docker
          command: docker build -t $DOCKER_USER/test-img:$VERSION --build-arg version=$VERSION .
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker push test-img
          command: docker push $DOCKER_USER/test-img:$VERSION

  deploy:
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Set env variables
            command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
        - run:
            name: Deploy-script-permission
            command: sudo chmod u+x ./deploy.sh
        - run:
            name: Deploy
            command: ./deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
